### ISSUE TITLE
Menu not setting active page

### ISSUE THREAD

**Issue by tellos88** [pewpewu/codeigniter-inspinia#1]
Hello there,

The menu creating function seems not to be recognizing the active page, any chance you can look into it?

**Comment by tellos88** [comment]
Hotfix

$(document).ready(function(){
	var url = window.location;
	$('ul a').filter(function () {
	   return this.href == url;
	}).parents('li').addClass('active').children('ul').addClass('collapse in');
});

**Comment by pewpewu** [comment]
fixed in next release
